# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe234e465c8aa0599d8b489233eb5458f6fbe6f304ef67a428f175db80b83da48603b6db641baec9c853690eb683aeb77e7e50da734c9c887bf940cdb387dcb

test:
  secret_key_base: 5b7042dd6405284f995ac69c1b7ce5673975299c603bc57e754637e678f1d4134bc030c5709fbfada2b35e5b0a3c1b3c9a38dac6bc28493dfec870cc1df5caa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
